#ifndef TRANSLATE_DE_H
#define TRANSLATE_DE_H

#define	TR__IN_CONFIGURATION_FILEI_WILL_IGNORE_IT	"' in Konfigurationsdatei...\nIch ignoriere das!"
#define	TR__WITH_VALUE_	"' mit Wert ''"
#define	TR_A_NUMBER_OR_A_VARIABLE_IS_MISSING_AFTER_MULTIPLICATION_OR_DIVISION_SIGN	"Nach dem Mal- oder Divisionszeichen fehlt eine Zahl oder Variable."
#define	TR_ADDRESS	"Adresse"
#define	TR_ALL_OK	"Alles ok"
#define	TR_BAUDRATE	"Baudrate"
#define	TR_BITINDEX	"Bit-Index"
#define	TR_CALL	"Aufruf"
#define	TR_CANCEL	"Abbrechen"
#define	TR_CANNOT_FIND_TAG_FOR_TEXT_TAG	"Konnte Tag für das Texttag nicht finden"
#define	TR_CANNOT_FIND_TAG_TO_OPEN_TAG	"Konnte kein schließendes Tag für das geöffnete Tag finden"
#define	TR_CHANNEL	"Kanal"
#define	TR_CHIP_DID_NOT_RESPOND_ON_SECOND_HELLOIS_A_PROGRAMM_RUNNING_THAT_SENDS_	"Das Board antwortete nicht auf das zweite 'Hallo'!\nLäuft ein Programm, das '{' schickt?"
#define	TR_CHIP_DID_NOT_RESPONDDIDNT_YOU_RESETIS_IT_TURNED_OFFIS_IT_CONNECTED	"Das Board antwortet gar nicht!\n\nHast du kein Reset ausgeführt?\nIst das Board angeschaltet?\nIst es angeschlossen?"
#define	TR_CHIP_DID_NOT_SEND_0X15IS_A_PROGRAMM_RUNNING_THAT_SENDS_	"Board sendete kein 0x15!\nLäuft ein Programm, das '{' sendet?"
#define	TR_CLOSING_TAG_WITH_CHILDS	"Ein Tag wurde geschlossen, obwohl nicht alle Kindelemente eingelesen wurden"
#define	TR_COMPILER_ERROR	"Compiler-Fehler:\n\n"
#define	TR_COMPILER_PATH	"Compiler-Pfad"
#define	TR_CONFIGURATION_ERROR	"Konfigurationsfehler"
#define	TR_CONTINUE	"Fortfahren?"
#define	TR_COULD_NOT_COMPILE_CODE_FOR_UNKNOWN_REASON	"Der Code konnte aus unerklärlichen Gründen nicht kompiliert werden."
#define	TR_COULD_NOT_CREATE_DIRECTORY	"Das temporäre Verzeichnis konnte nicht erstellt werden."
#define	TR_COULD_NOT_EXPORT_CODE	"Der Code konnte nicht exportiert werden."
#define	TR_COULD_NOT_OPEN_COMPORT	"Der serielle Port konnte nicht geöffnet werden."
#define	TR_COULD_NOT_READ_PROGRAM_FILE	"Die Programm-Datei konnte nicht gelesen werden."
#define	TR_COULD_NOT_REMOVE_TEMPORARY_DIRECTORY	"Das temporäre Verzeichnis konnte nicht gelöscht werden."
#define	TR_COULD_NOT_SAVE_CHANGED_PROGRAM_SETTINGS_INTO_	"Die geänderten Programmeinstellungen konnten nicht gespeichert werden. Pfad: "
#define	TR_COULD_NOT_SEND_PROGRAM	"Das Programm konnte nicht übertragen werden."
#define	TR_DATA	"Daten"
#define	TR_DECREMENT	"Dekrementerien"
#define	TR_DELAY	"Verzögere"
#define	TR_DID_NOT_RECEIVE_LAST_0X06	"Konnte letztes Zeichen(0x06) nicht empfangen."
#define	TR_DURATION	"Dauer"
#define	TR_EDIT_NAME	"Name bearbeiten"
#define	TR_EITHER_A_SECOND_QUOTATION_MARK_IS_MISSING_OR_THERE_ARE_TOO_MUCH_OF_THEM	"Entweder fehlt ein zweites Anführungszeichen oder du hast zu viele davon in der Zeichenkette!"
#define	TR_EMPTY_MATHEMATICAL_EXPRESSION	"Leerer mathematischer Ausdruck!"
#define	TR_END	"Ende"
#define	TR_ERROR_WITH_CONFIGURATION	"Konfigurationsfehler"
#define	TR_ERROR_WITH_SETTINGS	"Einstellungsfehler"
#define	TR_EXIT	"Beenden"
#define	TR_EXIT_NOT_POSSIBLE	"Beenden nicht möglich"
#define	TR_TRANSFER_ERROR	"Übertragungsfehler"
#define	TR_FAULTY_VALUE	"Wert fehlerhaft"
#define	TR_FINISHED_EXPORT_PRESS_OK_TO_DELETE_ALL_TEMPORARY_FILES	"Übertragen erfolgreich... Klicke OK, um alle temporären Dateien zu löschen"
#define	TR_FOUND_INVALID_KEY_	"Ungültiger Schlüssel gefunden '"
#define	TR_GET_ADC	"Lese ADC"
#define	TR_INCREMENT	"Inkrementerien"
#define	TR_INVALID_LINE_IN_CONFIGURATION_FILE	"Ungültige Zeile in der Konfigurationsdatei:\n"
#define	TR_INVALID_NUMBER	"Keine gültige Zahl"
#define	TR_INVALID_NUMBER_IN_TEXT_TAG	"Ungültige Zahl im Text-Tag"
#define	TR_IO_ERROR	"Eingabe/Ausgabe-Fehler"
#define	TR_LIMIT	"Limit"
#define	TR_MODULUS	"Modulus"
#define	TR_NAME_OF_THE_SUBPROGRAM	"Name des Unterprogramms:"
#define	TR_NEW	"Neu"
#define	TR_NO	"Nein"
#define	TR_NUMBER	"Zahl"
#define	TR_NUMBER_OR_VARIABLE_EXPECTED_BUT_THERE_IS_NONE	"Zahl oder Variable erwartet, es befindet sich aber keine hier"
#define	TR_OK	"OK"
#define	TR_OPEN	"Öffnen"
#define	TR_OPEN_BRACKET_WITHOUT_FURTHER_INSTRUCTIONS	"Öffnende Klammer ohne weitere Rechenanweisungen"
#define	TR_PARSE_ERROR	"Parserfehler"
#define	TR_PORT	"Port"
#define	TR_PRINT	"Ausgabe"
#define	TR_PROGRAM_SETTINGS	"Einstellungen"
#define	TR_EDIT_ALIASES	"Variablen"
#define	TR_PULSES	"Periodenlänge"
#define	TR_RANDOM_NUMBER	"Zufallszahl"
#define	TR_READ_KEY	"Lese Eingabe"
#define	TR_READ_MEMORY	"Lese Speicher"
#define	TR_RESET_BIT	"Bit loeschen"
#define	TR_RESET_YOUR_CHIP_NOW	"Starte das Board jetzt neu"
#define	TR_RESULT	"Ergebnis"
#define	TR_SAVE	"Speichern"
#define	TR_SAVE_AS	"Speichern unter"
#define	TR_SERIAL_PORT	"Serieller Port"
#define	TR_SET_BIT	"Bit setzen"
#define	TR_SOUND	"Ton"
#define	TR_START	"Start"
#define	TR_TEXT	"Text"
#define	TR_TEXT_TAG_WITH_CHILDS	"Texttag mit Kindelementen"
#define	TR_THIS_VARIABLE_DOES_NOT_EXISTS_HERE_HAVE_YOU_TYPED_IT_WRONG	"Diese Variable gibt es nicht! Hast du dich vielleicht vertippt?"
#define	TR_TODO_THROW_ERROR_HERE_	"!!!!! TODO !!!! Throw error!!!!"
#define	TR_TRANSFER	"Übertragen"
#define	TR_VARIABLE	"Variable"
#define	TR_WAIT_FOR_KEY	"Warte auf Eingabe"
#define	TR_WAIT_MICROSECONDS	"Warte Mikrosekunden"
#define	TR_WAIT_MILLISECONDS	"Warte Millisekunden"
#define	TR_WAIT_SECONDS	"Warte Sekunden"
#define	TR_WAIT_TIME	"Wartezeit"
#define	TR_WELL_I_WANTED_TO_REMOVE_A_NODE_THAT_ALREADY_HAS_BEEN_DELETED	""
#define	TR_WRITE_MEMORY	"Schreibe Speicher"
#define	TR_WRONG_DATA	"Falsche Angabe"
#define	TR_WRONG_OR_MISSING_OPERATOR	"Fehlendes oder falsches Rechenzeichen"
#define	TR_XML_PARSERCREATE_ERROR	"Fehelr des XML-Parsers"
#define	TR_YES	"Ja"
#define	TR_YOU_ENTERED_A_NUMBER_BUT_THIS_NUMBER_IS_TO_BIG_OR_NEGATIVE_THIS_IS_NOW_ALLOWED_HERE	"Du hast eine Zahl angegeben, diese ist aber zu groß bzw. negativ, was hier nicht sein darf."
#define	TR_YOU_ENTERED_A_NUMBER_BUT_YOU_MAY_NOT_ENTER_A_NUMBER_HERE	"Du hast eine Zahl angegeben, aber hier darf keie Zahl angegeben werden."
#define	TR_YOU_HAVE_ENTERED_AN_INVALID_NUMBER	"Es wurde keine gültige Zahl eingegeben"
#define	TR_YOU_OPENED_A_BRACKET_BUT_NEVER_CLOSED_IT	"Klammer wurde geöffnet, aber nie geschlossen"
#define	TR_YOU_STARTED_A_STRING_WITH_AN_QUOTATION_MARK_BUT_YOU_MAY_NOT_DO_THIS_HERE	"Du hast mit dem Anführungszeichen eine Zeichenkette begonnen, diese kann hier aber nicht verwendet werden"
#define	TR_UNSAVED	"Nicht gespeichert"
#define	TR_YES_SIDE_NOT_CONNECTED_WITH_A_BLOCK	"Ja-Seite ist nicht mit einem Block verbunden"
#define	TR_NO_SIDE_NOT_CONNECTED_WITH_A_BLOCK	"Nein-Seite ist nicht mit einem Block verbunden"
#define	TR_CONNECTOR_NOT_CONNECTED_WITH_ANOTHER_BLOCK	"Der Anschluss ist nicht mit einem anderen Block verbunden"
#define	TR_ASSIGNMENT	"Zuweisung"
#define	TR_IF_BLOCK	"Bedingungsblock"
#define	TR_INSTRUCTION	"Befehl"
#define	TR_SELECT_INSTRUCTION	"Befehl auswählen"
#define	TR_CALL_SUB	"Funktionsaufruf"
#define	TR_GENERATING_CODE	"Erzeuge Code"
#define	TR_COMPILING_CODE	"Kompiliere Code"
#define	TR_PLEASE_DO_RESET	"Bitte führe einen Reset durch"
#define	TR_SENDING_PROGRAM	"Sende Programm"
#define	TR_DO_YOU_WANT_TO_SAVE_YOUR_CHANGES	"Willst du die Änderungen an der Datei speichern, bevor sie geschlossen wird?"
#define	TR_SAVE_CHANGES	"Änderungen speichern?"
#define	TR_FILE_COULD_NOT_READ_IS_IT_INVALID	"Datei konnte nicht gelesen werden?\nIst sie ungültig oder beschädigt?"
#define	TR_READ_ERROR	"Lesefehler"
#define	TR_MISSING_SUBNAME_IN_CALL	"Du hast einen Aufruf für ein Unterprogramm eingefügt, aber kein Unterprogramm festgelegt, das aufgerufen werden soll!"
#define	TR_INVALID_NAME_SUPPLIED_JUST_CHARACTERS_AND_STARTING_WITH_THE_SECOND_NUMBERS_ARE_ALLOWED	"Du hast einen ungültigen Name angegeben!\nEs sind nur Buchstaben und erst ab dem zweiten Zeichen auch Zahlen erlaubt!"
#define	TR_INVALID_NAME	"Ungültiger Name"
#define	TR_CAN_NOT_DELETE_START_SUB	"Das Start-Unterprogramm kann nicht gelöscht werden"
#define	TR_DELETE_IMPOSSIBLE	"Löschen nicht möglich"
#define	TR_DO_YOU_REALLY_WANT_TO_DELETE_THE_SUB_AND_ALL_ITS_CONTENTS	"Willst du das Unterpgramm mitsamt allen Blöcken löschen?"
#define	TR_DELETE	"Löschen"
#define	TR_YOU_NEED_TO_FILL_IN_SOMETHING_HERE	"Du musst hier etwas angeben"
#define	TR_PRINTLN	"AusgabeZeile"
#define	TR_BLOCK_NOT_USED_FROM_ANYWHERE	"Dieser Block wird von keiner Stelle deines Programms benutzt!\nWenn du ihn nicht benötigst, lösche ihn!\nWenn du ihn aber benutzen willst, verbinde ihn mit einem Pfeil!"
#define	TR_COMMENT	"Kommentar"
#define	TR_EDIT_COMMENT	"Kommentar bearbeiten"
#define	TR_EDIT_ALIAS	"Alias bearbeiten"
#define	TR_CALL_SUB_EXPLANATION	"Dieser Block startet ein Unterprogramm, führt es vollständig aus und wechselt dann erst zum Block an der Pfeilspitze. Wähle das Unterprogramm hier aus:"
#define	TR_EDIT_ALIASES_EXPLANATION	"Hier kannst du den vorhandenen Variablen und Ports eigene Namen geben, damit dein Flussdiagramm noch verständlicher ist. Klicke doppelt auf einen Eintrag, um ihn zu verändern oder füge einen neuen hinzu."
#define	TR_ASSIGNMENT_EXPLANATION	"Eine Zuweisung gibt einer Variablen oder einem Port einen neuen Wert. Dabei kannst du den neuen Wert auch wieder von einer anderen Variable bzw. Pin abhängig machen oder sogar mit mathematischen Ausdrücken ändern. Mit 'intVariable0 = intVariable1 + 1' hat intVariable0 einen um 1 höheren Wert als intVariable1."
#define	TR_IF_EXPLANATION	"Eine Bedingung führt abhängig von einem mathematischen Ausdruck nur die Befehle an einem der beiden Pfeile aus. Die mathematischen Ausdrücke dürfen dabei als Gleichung oder Ungleichung formuliert sein. Trifft der Ausdruck zu, dann fährt das Programm mit dem Ja-Pfeil fort, sonst mit dem Nein-Pfeil."

#endif /* TRANSLATE_DE_H */