#ifndef TRANSLATE_EN_H
#define TRANSLATE_EN_H

#define	TR__IN_CONFIGURATION_FILEI_WILL_IGNORE_IT	"' in configuration file...\nI will ignore it!"
#define	TR__WITH_VALUE_	"' with value '"
#define	TR_A_NUMBER_OR_A_VARIABLE_IS_MISSING_AFTER_MULTIPLICATION_OR_DIVISION_SIGN	"A number or a variable is missing after multiplication or division sign."
#define	TR_ADDRESS	"Address"
#define	TR_ALL_OK	"All ok"
#define	TR_BAUDRATE	"Baudrate"
#define	TR_BITINDEX	"Bit-Index"
#define	TR_CALL	"Call"
#define	TR_CANCEL	"Cancel"
#define	TR_CANNOT_FIND_TAG_FOR_TEXT_TAG	"Cannot find tag for text tag"
#define	TR_CANNOT_FIND_TAG_TO_OPEN_TAG	"Cannot find tag to open tag"
#define	TR_CHANNEL	"Channel"
#define	TR_CHIP_DID_NOT_RESPOND_ON_SECOND_HELLOIS_A_PROGRAMM_RUNNING_THAT_SENDS_	"Chip did not respond on second hello!\nIs a programm running that sends '{'?"
#define	TR_CHIP_DID_NOT_RESPONDDIDNT_YOU_RESETIS_IT_TURNED_OFFIS_IT_CONNECTED	"Chip did not respond\n\nDidn't you reset?\nIs it turned off?\nIs it connected?"
#define	TR_CHIP_DID_NOT_SEND_0X15IS_A_PROGRAMM_RUNNING_THAT_SENDS_	"Chip did not send 0x15!\nIs a programm running that sends '{'?"
#define	TR_CLOSING_TAG_WITH_CHILDS	"Closing tag with childs"
#define	TR_COMPILER_ERROR	"Compiler error:\n\n"
#define	TR_COMPILER_PATH	"Compiler Path"
#define	TR_CONFIGURATION_ERROR	"Configuration error"
#define	TR_CONTINUE	"Continue?"
#define	TR_COULD_NOT_COMPILE_CODE_FOR_UNKNOWN_REASON	"Could not compile code for unknown reason"
#define	TR_COULD_NOT_CREATE_DIRECTORY	"Could not create temporary directory"
#define	TR_COULD_NOT_EXPORT_CODE	"Could not export code"
#define	TR_COULD_NOT_OPEN_COMPORT	"Could not open COM-port"
#define	TR_COULD_NOT_READ_PROGRAM_FILE	"Could not read program file!"
#define	TR_COULD_NOT_REMOVE_TEMPORARY_DIRECTORY	"Could not remove temporary directory"
#define	TR_COULD_NOT_SAVE_CHANGED_PROGRAM_SETTINGS_INTO_	"Could not save changed program settings into "
#define	TR_COULD_NOT_SEND_PROGRAM	"Could not send program!"
#define	TR_DATA	"Data"
#define	TR_DECREMENT	"Decrement"
#define	TR_DELAY	"Delay"
#define	TR_DID_NOT_RECEIVE_LAST_0X06	"Did not receive last 0x06"
#define	TR_DURATION	"Duration"
#define	TR_EDIT_NAME	"Edit name"
#define	TR_EITHER_A_SECOND_QUOTATION_MARK_IS_MISSING_OR_THERE_ARE_TOO_MUCH_OF_THEM	"Either a second quotation mark is missing or there are too much of them"
#define	TR_EMPTY_MATHEMATICAL_EXPRESSION	"Empty mathematical expression"
#define	TR_END	"End"
#define	TR_ERROR_WITH_CONFIGURATION	"Error with configuration"
#define	TR_ERROR_WITH_SETTINGS	"Error with settings"
#define	TR_EXIT	"Exit"
#define	TR_EXIT_NOT_POSSIBLE	"Exit not possible"
#define	TR_TRANSFER_ERROR	"Export error"
#define	TR_FAULTY_VALUE	"Faulty value"
#define	TR_FINISHED_EXPORT_PRESS_OK_TO_DELETE_ALL_TEMPORARY_FILES	"Finished export... Press OK to delete all temporary files"
#define	TR_FOUND_INVALID_KEY_	"Found invalid key '"
#define	TR_GET_ADC	"Get ADC"
#define	TR_INCREMENT	"Increment"
#define	TR_INVALID_LINE_IN_CONFIGURATION_FILE	"Invalid line in configuration file:\n"
#define	TR_INVALID_NUMBER	"Invalid number"
#define	TR_INVALID_NUMBER_IN_TEXT_TAG	"Invalid number in text tag"
#define	TR_IO_ERROR	"IO error"
#define	TR_LIMIT	"Limit"
#define	TR_MODULUS	"Modulus"
#define	TR_NAME_OF_THE_SUBPROGRAM	"Name of the subprogram"
#define	TR_NEW	"New"
#define	TR_NO	"No"
#define	TR_NUMBER	"Number"
#define	TR_NUMBER_OR_VARIABLE_EXPECTED_BUT_THERE_IS_NONE	"Number or variable expected, but there is none"
#define	TR_OK	"OK"
#define	TR_OPEN	"Open"
#define	TR_OPEN_BRACKET_WITHOUT_FURTHER_INSTRUCTIONS	"Open bracket without further instructions"
#define	TR_PARSE_ERROR	"Parse error"
#define	TR_PORT	"Port"
#define	TR_PRINT	"Print"
#define	TR_PROGRAM_SETTINGS	"Settings"
#define	TR_EDIT_ALIASES	"Aliases"
#define	TR_PULSES	"Pulses"
#define	TR_RANDOM_NUMBER	"Random number"
#define	TR_READ_KEY	"Read key"
#define	TR_READ_MEMORY	"Read memory"
#define	TR_RESET_BIT	"Reset bit"
#define	TR_RESET_YOUR_CHIP_NOW	"Reset your chip now"
#define	TR_RESULT	"Result"
#define	TR_SAVE	"Save"
#define	TR_SAVE_AS	"Save as"
#define	TR_SERIAL_PORT	"Serial Port"
#define	TR_SET_BIT	"Set Bit"
#define	TR_SOUND	"Sound"
#define	TR_START	"Start"
#define	TR_TEXT	"Text"
#define	TR_TEXT_TAG_WITH_CHILDS	"Text tag with childs"
#define	TR_THIS_VARIABLE_DOES_NOT_EXISTS_HERE_HAVE_YOU_TYPED_IT_WRONG	"This variable does not exists here! Have you typed it wrong?"
#define	TR_TODO_THROW_ERROR_HERE_	"!!!!!!TODO!!!!! Throw error here ;)"
#define	TR_TRANSFER	"Transfer"
#define	TR_VARIABLE	"Variable"
#define	TR_WAIT_FOR_KEY	"Wait for key"
#define	TR_WAIT_MICROSECONDS	"Wait microseconds"
#define	TR_WAIT_MILLISECONDS	"Wait milliseconds"
#define	TR_WAIT_SECONDS	"Wait seconds"
#define	TR_WAIT_TIME	"Wait time"
#define	TR_WELL_I_WANTED_TO_REMOVE_A_NODE_THAT_ALREADY_HAS_BEEN_DELETED	"Well... I wanted to remove a node, that already has been deleted!"
#define	TR_WRITE_MEMORY	"Write memory"
#define	TR_WRONG_DATA	"Wrong data"
#define	TR_WRONG_OR_MISSING_OPERATOR	"Wrong or missing operator"
#define	TR_XML_PARSERCREATE_ERROR	"XML_ParserCreate error"
#define	TR_YES	"Yes"
#define	TR_YOU_ENTERED_A_NUMBER_BUT_THIS_NUMBER_IS_TO_BIG_OR_NEGATIVE_THIS_IS_NOW_ALLOWED_HERE	"You entered a number, but this number is to big or negative. This is now allowed here."
#define	TR_YOU_ENTERED_A_NUMBER_BUT_YOU_MAY_NOT_ENTER_A_NUMBER_HERE	"You entered a number, but you may not enter a number here"
#define	TR_YOU_HAVE_ENTERED_AN_INVALID_NUMBER	"You have entered an invalid number"
#define	TR_YOU_OPENED_A_BRACKET_BUT_NEVER_CLOSED_IT	"You opened a bracket but never closed it"
#define	TR_YOU_STARTED_A_STRING_WITH_AN_QUOTATION_MARK_BUT_YOU_MAY_NOT_DO_THIS_HERE	"You started a string with an quotation mark but you may not do this here"
#define	TR_UNSAVED	"Unsaved"
#define	TR_YES_SIDE_NOT_CONNECTED_WITH_A_BLOCK	"Yes-side is not connected with a block"
#define	TR_NO_SIDE_NOT_CONNECTED_WITH_A_BLOCK	"No-side is not connected with a block"
#define	TR_CONNECTOR_NOT_CONNECTED_WITH_ANOTHER_BLOCK	"Connector is not connected with another block"
#define	TR_ASSIGNMENT	"Assignment"
#define	TR_IF_BLOCK	"If-Block"
#define	TR_INSTRUCTION	"Instruction"
#define	TR_SELECT_INSTRUCTION	"Select instruction"
#define	TR_CALL_SUB	"Call-Sub"
#define	TR_GENERATING_CODE	"Generating code"
#define	TR_COMPILING_CODE	"Compiling code"
#define	TR_PLEASE_DO_RESET	"Please do a reset"
#define	TR_SENDING_PROGRAM	"Sending program"
#define	TR_DO_YOU_WANT_TO_SAVE_YOUR_CHANGES	"Do you want to save the changes you have done to the file before closing it?"
#define	TR_SAVE_CHANGES	"Save changes?"
#define	TR_FILE_COULD_NOT_READ_IS_IT_INVALID	"File could not be read!\nIs it invalid or damaged?"
#define	TR_READ_ERROR	"Read error"
#define	TR_MISSING_SUBNAME_IN_CALL	"You put a call to a sub but have not specified what sub to call!"
#define	TR_INVALID_NAME_SUPPLIED_JUST_CHARACTERS_AND_STARTING_WITH_THE_SECOND_NUMBERS_ARE_ALLOWED	"You've entered an invalid name!\nOnly letters and, starting with the second char, numbers are allowed!"
#define	TR_INVALID_NAME	"Invalid name"
#define	TR_CAN_NOT_DELETE_START_SUB	"Cannot delte start-sub"
#define	TR_DELETE_IMPOSSIBLE	"Delete impossible"
#define	TR_DO_YOU_REALLY_WANT_TO_DELETE_THE_SUB_AND_ALL_ITS_CONTENTS	"Do you really want to delete the sub and all its contents?"
#define	TR_DELETE	"Delete"
#define	TR_YOU_NEED_TO_FILL_IN_SOMETHING_HERE	"You need to fill in something here"
#define	TR_PRINTLN	"Println"
#define	TR_BLOCK_NOT_USED_FROM_ANYWHERE	"This block is not used from anywhere in your programm\nIf it is not needed, just delete ist!\nIf you want to use it, please connect it with the end of a connector!"
#define	TR_COMMENT	"Comment"
#define	TR_EDIT_COMMENT	"Edit comment"
#define	TR_EDIT_ALIAS	"Edit alias"
#define	TR_CALL_SUB_EXPLANATION	"This block starts a sub-program, executes it until its end and then continues with the next block in the chain. Choose the sub-program to start in the list:"
#define	TR_EDIT_ALIASES_EXPLANATION	"Here you can give the existing variables and Ports names, to make your diagram more readable. Make a double-click on an item to change it or define a new one."
#define	TR_ASSIGNMENT_EXPLANATION	"An assignment changes the value of an variable or port. You can make the new value depend on the value of another variable or pin and even modify this by mathematical expressions. With 'intVariable0 = intVariable1 + 1', intVariable0 has a value of one more than intVariable1"
#define	TR_IF_EXPLANATION	"A condition executes the blocks at one of its side depending on a mathematical expression. Those expression may be equatations or inequatations. If the expression applies the yes-arrow is executed, else the no-arrow."

#endif /* TRANSLATE_EN_H */